In [1]:
# !pip install yfinance

In [2]:
import yfinance as yf

In [ ]:
TICKER = 'MSFT'

# Historical Data

In [4]:
yf.download(TICKER)

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open      Volume
Ticker            MSFT        MSFT        MSFT        MSFT        MSFT
Date
1986-03-13    0.059827    0.062498    0.054485    0.054485  1031788800
1986-03-14    0.061963    0.063032    0.059827    0.059827   308160000
1986-03-17    0.063032    0.063566    0.061963    0.061963   133171200
1986-03-18    0.061429    0.063566    0.060895    0.063032    67766400
1986-03-19    0.060361    0.061963    0.059827    0.061429    47894400
...                ...         ...         ...         ...         ...
2025-02-14  408.429993  408.910004  405.880005  407.790009    22758500
2025-02-18  409.640015  410.600006  406.500000  408.000000    21423100
2025-02-19  414.769989  415.489990  407.649994  407.880005    24114200
2025-02-20  416.130005  419.309998  412.540009  415.290009    23508700
2025-02-21  408.209991  418.049988  407.890015  417.339996    27448200

[9813 rows x 5 columns]

# Quote

In [5]:
info = yf.Ticker(TICKER).info

info['currentPrice'], info['previousClose'], info['ask'], info['bid']

(408.21, 416.13, 408.39, 408.23)

# Options

In [6]:
expirations = yf.Ticker(TICKER).options
expirations

('2025-02-28',
 '2025-03-07',
 '2025-03-14',
 '2025-03-21',
 '2025-03-28',
 '2025-04-04',
 '2025-04-17',
 '2025-05-16',
 '2025-06-20',
 '2025-07-18',
 '2025-08-15',
 '2025-09-19',
 '2025-12-19',
 '2026-01-16',
 '2026-03-20',
 '2026-06-18',
 '2026-12-18',
 '2027-01-15',
 '2027-06-17',
 '2027-12-17')

In [7]:
yf.Ticker(TICKER).option_chain(expirations[0]).calls.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,MSFT250228C00240000,2025-02-12 15:08:15+00:00,240.0,167.72,166.45,170.50,0.000000,0.000000,NaN,0,1.802735,True,REGULAR,USD
1,MSFT250228C00270000,2025-02-06 16:30:58+00:00,270.0,147.30,136.45,140.50,0.000000,0.000000,1.0,0,1.437503,True,REGULAR,USD
2,MSFT250228C00300000,2025-01-31 19:55:07+00:00,300.0,117.17,106.50,110.75,0.000000,0.000000,7.0,7,1.183598,True,REGULAR,USD
3,MSFT250228C00320000,2025-02-20 14:51:42+00:00,320.0,97.07,86.50,91.00,0.000000,0.000000,3.0,6,1.008794,True,REGULAR,USD
4,MSFT250228C00325000,2025-02-21 18:57:05+00:00,325.0,86.60,81.50,85.50,-3.099998,-3.455963,1.0,12,0.862306,True,REGULAR,USD

In [8]:
yf.Ticker(TICKER).option_chain(expirations[0]).puts.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,MSFT250228P00230000,2025-02-14 14:33:07+00:00,230.0,0.01,0.0,0.01,0.00,0.0,2.0,55,1.312503,False,REGULAR,USD
1,MSFT250228P00240000,2025-02-21 19:39:15+00:00,240.0,0.01,0.0,0.01,0.00,0.0,1082.0,25,1.218754,False,REGULAR,USD
2,MSFT250228P00260000,2025-02-21 19:37:55+00:00,260.0,0.01,0.0,0.01,0.00,0.0,1036.0,212,1.062505,False,REGULAR,USD
3,MSFT250228P00280000,2025-02-21 20:35:23+00:00,280.0,0.01,0.0,0.82,-0.01,-50.0,1079.0,107,1.410159,False,REGULAR,USD
4,MSFT250228P00290000,2025-02-21 19:45:28+00:00,290.0,0.02,0.0,2.01,0.01,100.0,938.0,11,1.502932,False,REGULAR,USD